plugins {
    id 'java'
}

group = 'de.teamholy'
version = '1.0'

ext {
    coreVersion='2.5.2'
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}


subprojects {
    apply plugin: 'java'

    repositories {
        maven { url "https://repo.dmulloy2.net/repository/public/" }
        maven {
            name = 'spigotmc-repo'
            url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
        }
        maven {
            name = 'sonatype'
            url = 'https://oss.sonatype.org/content/groups/public/'
        }
        maven {
            name 'koboo-reposilite'
            url 'https://reposilite.koboo.eu/releases'
        }
        maven { url "https://repo.glaremasters.me/repository/concuncan/" }
    }

    dependencies {
        compileOnly group: "com.comphenix.protocol", name: "ProtocolLib", version: "4.8.0";
        compileOnly 'org.spigotmc:spigot-api:1.8.8-R0.1-SNAPSHOT'
        compileOnly("de.teamholy:holy-core-api:$coreVersion");
        compileOnly "de.teamholy:bukkit-core-api:${coreVersion}"
        compileOnly "de.teamholy:bungee-core-api:${coreVersion}"
        compileOnly "de.teamholy:bukkit-markupapi:${coreVersion}"
        implementation 'eu.koboo:en2do:2.3.3'
        implementation 'io.netty:netty-codec:4.1.97.Final'
        compileOnly 'net.md-5:bungeecord-api:1.19-R0.1-SNAPSHOT'
        compileOnly 'org.bukkit:bukkit:1.8.8-R0.1-SNAPSHOT'
        compileOnly 'com.github.azbh111:craftbukkit-1.8.8:R'
        compileOnly 'org.mongodb:mongo-java-driver:3.12.8'
        implementation 'org.redisson:redisson:3.19.1'
        compileOnly 'de.dytanic.cloudnet:cloudnet-wrapper-jvm:3.4.0-RELEASE'
        compileOnly 'de.dytanic.cloudnet:cloudnet-syncproxy:3.4.0-RELEASE'
        compileOnly 'de.dytanic.cloudnet:cloudnet-bridge:3.4.0-RELEASE'
        implementation 'com.grinderwolf:slimeworldmanager-api:2.2.1'
        compileOnly 'com.gmail.filoghost.holographicdisplays:holographicdisplays-api:2.4.9'


    }
}

test {
    useJUnitPlatform()
}