name: Clutches
main: de.teamholy.clutches.Clutches
version: 1.0

depend: [ bukkit-core, SlimeWorldManager ]
softdepend:
  - SlimeWorldManager

commands:
  playgroundpreset:
  playworld:
  quit:
  spawn:
  vanish:
    aliases:
      - v