name: Clutches
main: de.teamholy.clutches.Clutches
version: 1.0

depend: [ API, bukkit-core, SlimeWorldManager ]
softdepend:
  - SlimeWorldManager

commands:
  playgroundpreset:
  playworld:
  quit:
  spawn: