plugins {
    id 'java'
    id("io.freefair.lombok") version "8.4"
}

group = 'de.teamholy'
version = '1.0'

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation fileTree(dir: 'lib', include: ['*.jar'])
    implementation 'com.google.code.gson:gson:2.10.1'

    implementation project(':API')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}


test {
    useJUnitPlatform()
}