name: knockbackffa
version: 1.0
author: yassino
main: de.teamholy.knockbackffa.KnockbackFFA

depend: [EffectLib, MarkupAPI]

commands:
  setup:
  quit:
  teaming:
    aliases: [tm, teams]
  vanish:
    aliases: [v]