plugins {
    id 'java'
    id("io.freefair.lombok") version "8.4"
}

group = 'de.teamholy'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    /**implementation('de.skydb.updater:Updater-Bukkit:0.0.3-SNAPSHOT')
    shadowJar {
        relocate('de.skydb.updater', 'de.teamholy.sgffa.updater')
    }**/
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}


test {
    useJUnitPlatform()
}